# Copyright 2016 Terence Parr, Sam Harwell, and Burt Harris
# All rights reserved.
# Licensed under the BSD-3-clause license. See LICENSE file in the project root for license information.

version: 1.0.{build}
image: Visual Studio 2015
init:
- git config --global core.autocrlf true
install:
- ps: Install-Product node 6
branches:
  only:
  - master
environment:
  JAVA6_HOME: C:/Program Files/Java/jdk1.6.0/jre
build_script:
- npm install
test_script:
- npm test
- mvn -B -f tool/pom.xml -Dgpg.skip=true -Psonatype-oss-release test
cache:
- node_modules -> **\package.json
- C:\Users\appveyor\.m2 -> **\pom.xml
