version: 1.0.{build}
image: Visual Studio 2015
init:
- git config --global core.autocrlf true
install:
- ps: >-
    Install-Product node 6

    npm install
branches:
  only:
  - master
build_script:
- mvn -B -f tool/pom.xml -DskipTests=true clean verify
test_script:
- npm test
cache:
- node_modules -> **\package.json
- C:\Users\appveyor\.m2 -> **\pom.xml
